name: "LaTeX Build with Docker"
description: "Builds a PDF file from LaTeX source using a Docker container."
runs:
  using: "docker"
  entrypoint: "/usr/src/entrypoint.sh"
  image: "docker://ghcr.io/smeetsee/latex-docker-action:latest"
  args:
    - ${{ inputs.tex_file }}
inputs:
  tex_file:
    description: "The entry point .tex file to compile."
    required: true